#!/usr/bin/env python3
"""Render the Claude config in this repo into the shapes other agent tools read.

Called by link-dotfiles.sh. Everything it writes is generated, so the source of
truth stays the one copy under claude/ and nothing has to be kept in sync by
hand. Same idea as the launchd plist rendering in that script, for the same
reason: the destination format is not a symlink target.

What comes out, and why each one is rendered rather than linked:

  ~/.codex/AGENTS.md          CLAUDE.md with @imports inlined, which Codex does
                              not resolve, and the Claude-only parts removed
  ~/.codex/agents/*.toml      the review agents, from markdown-with-frontmatter
                              into TOML with developer_instructions
  ~/.agents/skills/<cmd>/     the commands, as skills, because Codex has no
                              commands directory and enabled skills appear in
                              its slash-command list

The skills themselves are not here. They are already in the format every tool
reads, so link-dotfiles.sh symlinks those directly.
"""

import os
import re
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / "claude"
HOME = Path(os.environ.get("HOME", Path.home()))
CODEX = HOME / ".codex"
AGENTS = HOME / ".agents"

GENERATED = "<!-- Generated by dotfiles/lib/render-agent-configs.py. Edit the source under dotfiles/claude/, then re-run link-dotfiles.sh. -->"

# Sections of CLAUDE.md that describe machinery only Claude Code has. Matched on
# the heading line; everything up to the next heading at the same level goes.
CLAUDE_ONLY_SECTIONS = [
    "### 8. Neutral phrasing for security findings",
]

# Imports to inline, in the order they appear. RTK is deliberately absent: it is
# driven by a Claude Code bash hook that rewrites commands, and a tool without
# that hook would read the reference and try to call a proxy that never fires.
INLINE_IMPORTS = ["writing-style.md"]

# Wording that names a Claude tool where the instruction itself is general.
REPHRASE = [
    (
        "Always use the `AskUserQuestion` tool to get clarity before acting.",
        "Always stop and ask the user before acting.",
    ),
    ("If uncertain, ask via `AskUserQuestion`.", "If uncertain, ask."),
    (
        "If multiple interpretations exist, ask which one — don't pick silently.",
        "If multiple interpretations exist, ask which one, and do not pick silently.",
    ),
    ("Name what's confusing. Ask via `AskUserQuestion`.", "Name what's confusing and ask."),
]


def strip_sections(text, headings):
    out, skipping, skip_level = [], False, 0
    for line in text.split("\n"):
        m = re.match(r"^(#+)\s", line)
        if skipping and m and len(m.group(1)) <= skip_level:
            skipping = False
        if not skipping and any(line.startswith(h) for h in headings):
            skipping, skip_level = True, len(m.group(1))
            continue
        if not skipping:
            out.append(line)
    return "\n".join(out)


def render_codex_agents_md():
    text = (SRC / "CLAUDE.md").read_text()

    for old, new in REPHRASE:
        text = text.replace(old, new)

    text = strip_sections(text, CLAUDE_ONLY_SECTIONS)

    # Drop every @import line, then append back the ones worth carrying.
    kept = []
    for name in INLINE_IMPORTS:
        p = SRC / name
        if p.exists():
            kept.append(f"\n---\n\n{p.read_text().strip()}\n")
    text = re.sub(r"^@\S+\.md\s*$", "", text, flags=re.M).rstrip()

    body = f"{GENERATED}\n\n{text}\n{''.join(kept)}"
    CODEX.mkdir(parents=True, exist_ok=True)
    (CODEX / "AGENTS.md").write_text(body)
    return CODEX / "AGENTS.md"


def split_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n+(.*)$", text, re.S)
    return (m.group(1), m.group(2)) if m else ("", text)


def field(frontmatter, key):
    m = re.search(rf"^{key}:\s*(.+)$", frontmatter, re.M)
    return m.group(1).strip().strip("\"'") if m else None


def describe(frontmatter, body, fallback):
    d = field(frontmatter, "description")
    if d:
        return d
    for line in body.split("\n"):
        line = line.strip()
        if line and not line.startswith(("#", "<!--")):
            return line[:300]
    return fallback


def render_codex_agents():
    written = []
    d = CODEX / "agents"
    d.mkdir(parents=True, exist_ok=True)
    for f in sorted((SRC / "agents").glob("*.md")):
        fm, body = split_frontmatter(f.read_text())
        name = (field(fm, "name") or f.stem).replace("-", "_")
        desc = describe(fm, body, f"The {f.stem} review pass.").replace('"', "'")
        # A TOML multiline basic string cannot contain a bare triple quote.
        body = body.replace('"""', "'''").strip()
        out = d / f"{name}.toml"
        out.write_text(
            f"# Generated by dotfiles/lib/render-agent-configs.py from claude/agents/{f.name}.\n"
            f"# Edit that file, then re-run link-dotfiles.sh.\n"
            f'name = "{name}"\n'
            f'description = "{desc}"\n'
            f'sandbox_mode = "read-only"\n'
            f'developer_instructions = """\n{body}\n"""\n'
        )
        written.append(out)
    return written


def render_commands_as_skills():
    written = []
    d = AGENTS / "skills"
    d.mkdir(parents=True, exist_ok=True)
    for f in sorted((SRC / "commands").glob("*.md")):
        fm, body = split_frontmatter(f.read_text())
        name = f.stem
        desc = describe(fm, body, f"The {name} command.").replace('"', "'")
        hint = field(fm, "argument-hint")
        # Claude substitutes $ARGUMENTS before the command body is read. Nothing
        # else does, so the token survives into the skill and has to be
        # explained rather than left looking like a variable that got missed.
        args = ""
        if hint or "$ARGUMENTS" in body:
            shape = f" Expected shape: `{hint}`." if hint else ""
            args = (
                f"\nRead `$ARGUMENTS` below as whatever the user said when they "
                f"invoked this, and treat it as empty if they said nothing "
                f"beyond the name.{shape}\n"
            )
        skill = d / name
        skill.mkdir(parents=True, exist_ok=True)
        (skill / "SKILL.md").write_text(
            f"---\nname: {name}\ndescription: {desc}\n---\n\n"
            f"{GENERATED}\n{args}\n{body.strip()}\n"
        )
        written.append(skill / "SKILL.md")
    return written


def main():
    if not SRC.is_dir():
        print(f"no claude/ directory at {SRC}", file=sys.stderr)
        return 1
    a = render_codex_agents_md()
    b = render_codex_agents()
    c = render_commands_as_skills()
    print(f"rendered {a}")
    print(f"rendered {len(b)} Codex agents into {CODEX / 'agents'}")
    print(f"rendered {len(c)} commands as skills into {AGENTS / 'skills'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
